version: '3'
services:
  rbase: 
    image: aabor/rbase
    build: rbase/.
    container_name: rbase
    volumes:
      - ~/Documents/Trading/fh_data-dev:/home/docker/fh/data
      - ~/Dropbox/mt4/data-dev:/home/docker/fh/data/mt4
      # SSH keys
      - ~/.ssh:/home/docker/.ssh/  
      # Secrets
      - ~/.secrets:/home/docker/.secrets/  
    ports:
      - "8787:8787"
      - "3838:3838"
    environment:
      - TZ="Europe/Kiev"
      - USER=docker
      - PASSWORD=123
      - GIT_VERSION=$GIT_VERSION
    restart: always
  rbase-finance: 
    image: aabor/rbase-finance
    build: rbase-finance/.
    volumes:
      - ~/Documents/Trading/fh_data-dev:/home/docker/fh/data
      - ~/Dropbox/mt4/data-dev:/home/docker/fh/data/mt4
      # SSH keys
      - ~/.ssh:/home/docker/.ssh/  
      # Secrets
      - ~/.secrets:/home/docker/.secrets/  
    ports:
      - "8788:8787"
      - "3839:3838"
    environment:
      - TZ="Europe/Kiev"
      - USER=docker
      - PASSWORD=123
      - GIT_VERSION=$GIT_VERSION
    restart: always
  rbase-text: 
    image: aabor/rbase-text
    build: rbase-text/.
    container_name: rbase-text
    volumes:
      - ~/Documents/Trading/fh_data-dev:/home/docker/fh/data
      - ~/Dropbox/mt4/data-dev:/home/docker/fh/data/mt4
      # SSH keys
      - ~/.ssh:/home/docker/.ssh/  
      # Secrets
      - ~/.secrets:/home/docker/.secrets/  
    ports:
      - "8789:8787"
      - "3840:3838"
    environment:
      - TZ="Europe/Kiev"
      - USER=docker
      - PASSWORD=123
      - GIT_VERSION=$GIT_VERSION
    restart: always
