version: '3'
services:
  rbase: 
    image: aabor/rbase
    build: rbase/.
    container_name: rbase
    volumes:
      - /home/$USER/Selenium:/home/docker/Selenium
      - /home/$USER/Documents/Trading/fh_data-dev:/home/docker/fh/data
      - /home/$USER/Dropbox/mt4/data-dev:/home/docker/fh/data/mt4
      # SSH keys
      - /home/$USER/.ssh:/home/docker/.ssh/  
      # Secrets
      - /home/$USER/.secrets:/home/docker/.secrets/  
    ports:
      - "8787:8787"
      - "3838:3838"
    environment:
      - USER=rstudio
      - PASSWORD=123
    restart: always
  rbase-finance: 
    image: aabor/rbase-finance
    build: rbase-finance/.
    container_name: rbase-finance
    volumes:
      - /home/$USER/Selenium:/home/docker/Selenium
      - /home/$USER/Documents/Trading/fh_data-dev:/home/docker/fh/data
      - /home/$USER/Dropbox/mt4/data-dev:/home/docker/fh/data/mt4
      # SSH keys
      - /home/$USER/.ssh:/home/docker/.ssh/  
      # Secrets
      - /home/$USER/.secrets:/home/docker/.secrets/  
    ports:
      - "8788:8787"
      - "3839:3838"
    environment:
      - USER=rstudio
      - PASSWORD=123
    restart: always
  rbase-text: 
    image: aabor/rbase-text
    build: rbase-text/.
    container_name: rbase-text
    volumes:
      - /home/$USER/Selenium:/home/docker/Selenium
      - /home/$USER/Documents/Trading/fh_data-dev:/home/docker/fh/data
      - /home/$USER/Dropbox/mt4/data-dev:/home/docker/fh/data/mt4
      # SSH keys
      - /home/$USER/.ssh:/home/docker/.ssh/  
      # Secrets
      - /home/$USER/.secrets:/home/docker/.secrets/  
    ports:
      - "8789:8787"
      - "3840:3838"
    environment:
      - USER=rstudio
      - PASSWORD=123
    restart: always
